version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/mongodb
    networks:
      - nest_network

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo
    networks:
      - nest_network

networks:
  nest_network:
    driver: bridge
